package com.team2.documents.entity;

import java.util.Set;

public class PurchaseOrder {

    private final String poId;
    private PurchaseOrderStatus status;

    public PurchaseOrder(String poId) {
        this.poId = poId;
        this.status = PurchaseOrderStatus.DRAFT;
    }

    public PurchaseOrder(String poId, PurchaseOrderStatus status) {
        this.poId = poId;
        this.status = status;
    }

    public String getPoId() {
        return poId;
    }

    public PurchaseOrderStatus getStatus() {
        return status;
    }

    public static PurchaseOrderStatus determineInitialStatus(PositionLevel positionLevel) {
        if (PositionLevel.MANAGER.equals(positionLevel)) {
            return PurchaseOrderStatus.CONFIRMED;
        }
        return PurchaseOrderStatus.APPROVAL_PENDING;
    }

    public void requestRegistration() {
        if (!PurchaseOrderStatus.DRAFT.equals(status)) {
            throw new IllegalStateException("초안 상태의 PO만 등록 요청할 수 있습니다.");
        }
        this.status = PurchaseOrderStatus.APPROVAL_PENDING;
    }

    public void confirmRegistration() {
        if (!PurchaseOrderStatus.DRAFT.equals(status)) {
            throw new IllegalStateException("초안 상태의 PO만 즉시 확정할 수 있습니다.");
        }
        this.status = PurchaseOrderStatus.CONFIRMED;
    }

    public void requestModification() {
        if (!PurchaseOrderStatus.CONFIRMED.equals(status)) {
            throw new IllegalStateException("확정 상태의 PO만 수정 요청할 수 있습니다.");
        }
        this.status = PurchaseOrderStatus.APPROVAL_PENDING;
    }

    public void requestDeletion() {
        if (!PurchaseOrderStatus.CONFIRMED.equals(status)) {
            throw new IllegalStateException("확정 상태의 PO만 삭제 요청할 수 있습니다.");
        }
        this.status = PurchaseOrderStatus.APPROVAL_PENDING;
    }

    public void approve() {
        if (!PurchaseOrderStatus.APPROVAL_PENDING.equals(status)) {
            throw new IllegalStateException("결재대기 상태의 PO만 승인할 수 있습니다.");
        }
        this.status = PurchaseOrderStatus.CONFIRMED;
    }

    public void reject() {
        if (!PurchaseOrderStatus.APPROVAL_PENDING.equals(status)) {
            throw new IllegalStateException("결재대기 상태의 PO만 반려할 수 있습니다.");
        }
        this.status = PurchaseOrderStatus.REJECTED;
    }

    public Set<GeneratedDocumentType> getAutoGeneratedDocumentsOnConfirmation() {
        if (!PurchaseOrderStatus.CONFIRMED.equals(status)) {
            throw new IllegalStateException("확정 상태의 PO만 자동 생성 문서를 가질 수 있습니다.");
        }
        return Set.of(
                GeneratedDocumentType.COMMERCIAL_INVOICE,
                GeneratedDocumentType.PACKING_LIST,
                GeneratedDocumentType.SHIPMENT_ORDER
        );
    }

    public Set<GeneratedDocumentType> getSelectableGeneratedDocuments() {
        if (!PurchaseOrderStatus.CONFIRMED.equals(status)) {
            throw new IllegalStateException("확정 상태의 PO만 선택 생성 문서를 가질 수 있습니다.");
        }
        return Set.of(GeneratedDocumentType.PRODUCTION_ORDER);
    }

    public void validateModifiable(ShipmentStatus shipmentStatus) {
        if (ShipmentStatus.COMPLETED.equals(shipmentStatus)) {
            throw new IllegalStateException("출하완료 상태의 PO는 수정할 수 없습니다.");
        }
    }

    public void validateDeletable(ShipmentStatus shipmentStatus) {
        if (ShipmentStatus.COMPLETED.equals(shipmentStatus)) {
            throw new IllegalStateException("출하완료 상태의 PO는 삭제할 수 없습니다.");
        }
    }
}
