package com.team2.documents.entity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.Set;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class PurchaseOrderDocumentGenerationTest {

    @Test
    @DisplayName("확정 상태의 PO는 CI, PL, 출하지시서를 자동 생성 대상으로 가진다")
    void getAutoGeneratedDocuments_whenPurchaseOrderIsConfirmed_thenReturnsAutoGeneratedDocuments() {
        // given
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO2025-0001", PurchaseOrderStatus.CONFIRMED);

        // when
        Set<GeneratedDocumentType> generatedDocumentTypes = purchaseOrder.getAutoGeneratedDocumentsOnConfirmation();

        // then
        assertEquals(Set.of(
                GeneratedDocumentType.COMMERCIAL_INVOICE,
                GeneratedDocumentType.PACKING_LIST,
                GeneratedDocumentType.SHIPMENT_ORDER
        ), generatedDocumentTypes);
    }

    @Test
    @DisplayName("확정 상태가 아닌 PO는 자동 생성 대상 문서를 가질 수 없다")
    void getAutoGeneratedDocuments_whenPurchaseOrderIsNotConfirmed_thenThrowsException() {
        // given
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO2025-0001", PurchaseOrderStatus.APPROVAL_PENDING);

        // when & then
        assertThrows(IllegalStateException.class, purchaseOrder::getAutoGeneratedDocumentsOnConfirmation);
    }

    @Test
    @DisplayName("확정 상태의 PO는 생산지시서를 선택 생성 대상으로 가진다")
    void getSelectableGeneratedDocuments_whenPurchaseOrderIsConfirmed_thenReturnsProductionOrder() {
        // given
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO2025-0001", PurchaseOrderStatus.CONFIRMED);

        // when
        Set<GeneratedDocumentType> generatedDocumentTypes = purchaseOrder.getSelectableGeneratedDocuments();

        // then
        assertEquals(Set.of(GeneratedDocumentType.PRODUCTION_ORDER), generatedDocumentTypes);
    }

    @Test
    @DisplayName("확정 상태가 아닌 PO는 생산지시서를 선택 생성할 수 없다")
    void getSelectableGeneratedDocuments_whenPurchaseOrderIsNotConfirmed_thenThrowsException() {
        // given
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO2025-0001", PurchaseOrderStatus.APPROVAL_PENDING);

        // when & then
        assertThrows(IllegalStateException.class, purchaseOrder::getSelectableGeneratedDocuments);
    }
}
