package com.team2.documents.command.application.service;

import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class DocumentLinkServiceTest {

    @Mock
    private DocumentLinkMutationService documentLinkMutationService;

    @InjectMocks
    private DocumentLinkService documentLinkService;

    @Test
    @DisplayName("PI ID가 비어 있으면 PO-PI 링크를 생성하지 않는다")
    void linkPurchaseOrderToProformaInvoice_whenPiIdIsBlank_thenDoesNothing() {
        documentLinkService.linkPurchaseOrderToProformaInvoice("PO260001", " ");

        verify(documentLinkMutationService, never()).linkPurchaseOrderToProformaInvoice("PO260001", " ");
    }

    @Test
    @DisplayName("자동 생성 문서 링크는 mutation 서비스에 위임한다")
    void linkAutoGeneratedDocuments_whenCalled_thenDelegates() {
        doNothing().when(documentLinkMutationService)
                .linkAutoGeneratedDocuments("PO260001", "CI260001", "PL260001", "SO260001");

        documentLinkService.linkAutoGeneratedDocuments("PO260001", "CI260001", "PL260001", "SO260001");

        verify(documentLinkMutationService)
                .linkAutoGeneratedDocuments("PO260001", "CI260001", "PL260001", "SO260001");
    }
}
