package com.team2.documents.command.application.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.team2.documents.command.domain.entity.ProductionOrder;
import com.team2.documents.command.domain.entity.ProformaInvoice;
import com.team2.documents.command.domain.entity.PurchaseOrder;
import com.team2.documents.command.domain.entity.ShipmentOrder;
import com.team2.documents.command.domain.entity.enums.ProformaInvoiceStatus;
import com.team2.documents.command.domain.entity.enums.PurchaseOrderStatus;
import com.team2.documents.command.domain.repository.ProductionOrderRepository;
import com.team2.documents.command.domain.repository.ShipmentOrderJpaRepository;

@ExtendWith(MockitoExtension.class)
class DocumentLinkMutationServiceTest {

    @Mock
    private PurchaseOrderCommandService purchaseOrderCommandService;

    @Mock
    private ProformaInvoiceCommandService proformaInvoiceCommandService;

    @Mock
    private ShipmentOrderJpaRepository shipmentOrderJpaRepository;

    @Mock
    private ProductionOrderRepository productionOrderRepository;

    @Mock
    private DocumentLinkBuilderService documentLinkBuilderService;

    @InjectMocks
    private DocumentLinkMutationService documentLinkMutationService;

    @Test
    @DisplayName("PO와 PI를 서로 linkedDocuments에 연결한다")
    void linkPurchaseOrderToProformaInvoice_whenCalled_thenUpdatesBothDocuments() {
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO260001", PurchaseOrderStatus.CONFIRMED);
        purchaseOrder.setLinkedDocuments("[]");
        ProformaInvoice proformaInvoice = new ProformaInvoice("PI260001", ProformaInvoiceStatus.CONFIRMED);
        proformaInvoice.setLinkedDocuments("[]");

        when(purchaseOrderCommandService.findById("PO260001")).thenReturn(purchaseOrder);
        when(proformaInvoiceCommandService.findById("PI260001")).thenReturn(proformaInvoice);
        when(documentLinkBuilderService.append("[]", "PI260001", "PI", "CONFIRMED"))
                .thenReturn("[{\"id\":\"PI260001\",\"type\":\"PI\"}]");
        when(documentLinkBuilderService.append("[]", "PO260001", "PO", "CONFIRMED"))
                .thenReturn("[{\"id\":\"PO260001\",\"type\":\"PO\"}]");

        documentLinkMutationService.linkPurchaseOrderToProformaInvoice("PO260001", "PI260001");

        assertEquals("[{\"id\":\"PI260001\",\"type\":\"PI\"}]", purchaseOrder.getLinkedDocuments());
        assertEquals("[{\"id\":\"PO260001\",\"type\":\"PO\"}]", proformaInvoice.getLinkedDocuments());
        verify(purchaseOrderCommandService).save(purchaseOrder);
        verify(proformaInvoiceCommandService).save(proformaInvoice);
    }

    @Test
    @DisplayName("자동 생성 문서를 PO와 SO linkedDocuments에 반영한다")
    void linkAutoGeneratedDocuments_whenShipmentOrderExists_thenUpdatesPurchaseOrderAndShipmentOrder() {
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO260001", PurchaseOrderStatus.CONFIRMED);
        purchaseOrder.setLinkedDocuments("[]");
        purchaseOrder.setPiId("PI260001");

        ShipmentOrder shipmentOrder = new ShipmentOrder();
        shipmentOrder.setShipmentOrderCode("SO260001");
        shipmentOrder.setLinkedDocuments("[]");

        when(purchaseOrderCommandService.findById("PO260001")).thenReturn(purchaseOrder);
        when(shipmentOrderJpaRepository.findByShipmentOrderCode("SO260001")).thenReturn(Optional.of(shipmentOrder));
        when(documentLinkBuilderService.append("[]", "CI260001", "CI", "발행대기"))
                .thenReturn("[{\"id\":\"CI260001\"}]");
        when(documentLinkBuilderService.append("[{\"id\":\"CI260001\"}]", "PL260001", "PL", "발행대기"))
                .thenReturn("[{\"id\":\"CI260001\"},{\"id\":\"PL260001\"}]");
        when(documentLinkBuilderService.append("[{\"id\":\"CI260001\"},{\"id\":\"PL260001\"}]", "SO260001", "SO", "출하준비"))
                .thenReturn("[{\"id\":\"CI260001\"},{\"id\":\"PL260001\"},{\"id\":\"SO260001\"}]");
        when(documentLinkBuilderService.append("[]", "PO260001", "PO", "CONFIRMED"))
                .thenReturn("[{\"id\":\"PO260001\"}]");
        when(documentLinkBuilderService.append("[{\"id\":\"PO260001\"}]", "PI260001", "PI", "CONFIRMED"))
                .thenReturn("[{\"id\":\"PO260001\"},{\"id\":\"PI260001\"}]");

        documentLinkMutationService.linkAutoGeneratedDocuments("PO260001", "CI260001", "PL260001", "SO260001");

        assertEquals("[{\"id\":\"CI260001\"},{\"id\":\"PL260001\"},{\"id\":\"SO260001\"}]", purchaseOrder.getLinkedDocuments());
        assertEquals("[{\"id\":\"PO260001\"},{\"id\":\"PI260001\"}]", shipmentOrder.getLinkedDocuments());
        verify(purchaseOrderCommandService).save(purchaseOrder);
        verify(shipmentOrderJpaRepository).save(shipmentOrder);
    }

    @Test
    @DisplayName("생산지시 문서 연결 시 PO linkedDocuments와 생산지시 PO 코드를 갱신한다")
    void linkProductionOrder_whenProductionOrderExists_thenUpdatesPurchaseOrderAndProductionOrder() {
        PurchaseOrder purchaseOrder = new PurchaseOrder("PO260001", PurchaseOrderStatus.CONFIRMED);
        purchaseOrder.setLinkedDocuments("[]");
        ProductionOrder productionOrder = new ProductionOrder(
                "MO260001",
                1L,
                null,
                LocalDate.of(2026, 4, 7),
                1,
                2L,
                LocalDate.of(2026, 4, 20),
                "진행중",
                "ACME",
                "KOREA",
                "Kim",
                "Steel Coil",
                null,
                LocalDateTime.now(),
                LocalDateTime.now()
        );

        when(purchaseOrderCommandService.findById("PO260001")).thenReturn(purchaseOrder);
        when(productionOrderRepository.findByProductionOrderCode("MO260001")).thenReturn(Optional.of(productionOrder));
        when(documentLinkBuilderService.append("[]", "MO260001", "MO", "진행중"))
                .thenReturn("[{\"id\":\"MO260001\",\"type\":\"MO\"}]");

        documentLinkMutationService.linkProductionOrder("PO260001", "MO260001");

        assertEquals("[{\"id\":\"MO260001\",\"type\":\"MO\"}]", purchaseOrder.getLinkedDocuments());
        assertEquals("PO260001", productionOrder.getPoId());
        verify(purchaseOrderCommandService).save(purchaseOrder);
        verify(productionOrderRepository).save(productionOrder);
    }
}
