package com.team2.documents.command.application.service;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.team2.documents.command.domain.entity.CommercialInvoice;
import com.team2.documents.command.domain.entity.PackingList;
import com.team2.documents.command.domain.entity.PurchaseOrder;
import com.team2.documents.command.domain.entity.enums.PurchaseOrderStatus;
import com.team2.documents.command.domain.repository.CommercialInvoiceJpaRepository;
import com.team2.documents.command.domain.repository.CommercialInvoiceRepository;
import com.team2.documents.command.domain.repository.PackingListJpaRepository;
import com.team2.documents.command.domain.repository.PackingListRepository;
import com.team2.documents.command.domain.repository.ShipmentOrderJpaRepository;
import com.team2.documents.command.domain.repository.ShipmentOrderRepository;
import com.team2.documents.command.domain.entity.ShipmentOrder;

@ExtendWith(MockitoExtension.class)
class PurchaseOrderDocumentGenerationServiceTest {

    @Mock
    private PurchaseOrderCommandService purchaseOrderCommandService;

    @Mock
    private CommercialInvoiceRepository commercialInvoiceRepository;

    @Mock
    private CommercialInvoiceJpaRepository commercialInvoiceJpaRepository;

    @Mock
    private PackingListRepository packingListRepository;

    @Mock
    private PackingListJpaRepository packingListJpaRepository;

    @Mock
    private ShipmentOrderRepository shipmentOrderRepository;

    @Mock
    private ShipmentOrderJpaRepository shipmentOrderJpaRepository;

    @Mock
    private DocumentNumberGeneratorService documentNumberGeneratorService;

    @Mock
    private DocumentLinkService documentLinkService;

    @Mock
    private DocumentRevisionHistoryService documentRevisionHistoryService;

    @Mock
    private DocsSnapshotService docsSnapshotService;

    @Mock
    private DocumentAutoMailService documentAutoMailService;

    @InjectMocks
    private PurchaseOrderDocumentGenerationService purchaseOrderDocumentGenerationService;

    @Test
    @DisplayName("확정 상태의 PO는 CI, PL, 출하지시서를 자동 생성한다")
    void generateDocuments_whenPurchaseOrderIsConfirmed_thenCreatesAutoGeneratedDocuments() {
        // given
        String poId = "PO2025-0001";
        PurchaseOrder purchaseOrder = new PurchaseOrder(poId, PurchaseOrderStatus.CONFIRMED);

        when(purchaseOrderCommandService.findById(poId)).thenReturn(purchaseOrder);
        when(documentNumberGeneratorService.nextCommercialInvoiceId()).thenReturn("CI260001");
        when(documentNumberGeneratorService.nextPackingListId()).thenReturn("PL260001");
        when(documentNumberGeneratorService.nextShipmentOrderId()).thenReturn("SO260001");
        CommercialInvoice commercialInvoice = new CommercialInvoice();
        commercialInvoice.setCiId("CI260001");
        commercialInvoice.setPoId(1L);
        PackingList packingList = new PackingList();
        packingList.setPlId("PL260001");
        packingList.setPoId(1L);
        when(commercialInvoiceJpaRepository.findByCiCode("CI260001")).thenReturn(Optional.of(commercialInvoice));
        when(packingListJpaRepository.findByPlCode("PL260001")).thenReturn(Optional.of(packingList));
        ShipmentOrder shipmentOrder = new ShipmentOrder();
        shipmentOrder.setShipmentOrderId("SO260001");
        shipmentOrder.setPoId(1L);
        when(shipmentOrderJpaRepository.findByShipmentOrderCode("SO260001")).thenReturn(Optional.of(shipmentOrder));

        // when
        purchaseOrderDocumentGenerationService.generateOnConfirmation(poId);

        // then
        verify(commercialInvoiceRepository).createFromPurchaseOrder(poId, "CI260001");
        verify(packingListRepository).createFromPurchaseOrder(poId, "PL260001");
        verify(shipmentOrderRepository).createFromPurchaseOrder(poId, "SO260001");
        verify(docsSnapshotService).saveCommercialInvoiceSnapshot(commercialInvoice, purchaseOrder);
        verify(docsSnapshotService).savePackingListSnapshot(packingList, purchaseOrder);
        verify(documentAutoMailService).sendShipmentOrderToShippingTeam(purchaseOrder, shipmentOrder);
        verify(documentLinkService).linkAutoGeneratedDocuments(poId, "CI260001", "PL260001", "SO260001");
        verify(documentRevisionHistoryService).recordPurchaseOrderEvent(
                poId,
                "GENERATE_FOLLOW_UP_DOCUMENTS",
                purchaseOrder.getManagerId(),
                purchaseOrder.getStatus().name(),
                "CI/PL/SO 문서를 자동 생성했습니다."
        );
    }

    @Test
    @DisplayName("PO 정보가 없으면 자동 생성 시 예외가 발생한다")
    void generateDocuments_whenPurchaseOrderDoesNotExist_thenThrowsException() {
        // given
        String poId = "PO2025-9999";
        when(purchaseOrderCommandService.findById(poId))
                .thenThrow(new IllegalArgumentException("PO 정보를 찾을 수 없습니다."));

        // when & then
        assertThrows(IllegalArgumentException.class,
                () -> purchaseOrderDocumentGenerationService.generateOnConfirmation(poId));
    }

    @Test
    @DisplayName("확정 상태가 아닌 PO는 자동 생성할 수 없다")
    void generateDocuments_whenPurchaseOrderIsNotConfirmed_thenThrowsException() {
        // given
        String poId = "PO2025-0001";
        PurchaseOrder purchaseOrder = new PurchaseOrder(poId, PurchaseOrderStatus.APPROVAL_PENDING);

        when(purchaseOrderCommandService.findById(poId)).thenReturn(purchaseOrder);

        // when & then
        assertThrows(IllegalStateException.class,
                () -> purchaseOrderDocumentGenerationService.generateOnConfirmation(poId));
    }
}
