package com.team2.documents.command.application.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.team2.documents.command.domain.entity.CommercialInvoice;
import com.team2.documents.command.domain.entity.PackingList;
import com.team2.documents.command.domain.entity.ProformaInvoice;
import com.team2.documents.command.domain.entity.PurchaseOrder;
import com.team2.documents.command.domain.entity.ShipmentOrder;
import com.team2.documents.command.domain.entity.ProductionOrder;
import com.team2.documents.command.domain.repository.CommercialInvoiceJpaRepository;
import com.team2.documents.command.domain.repository.PackingListJpaRepository;
import com.team2.documents.command.domain.repository.ProductionOrderRepository;
import com.team2.documents.command.domain.repository.ShipmentOrderJpaRepository;

@Service
@Transactional
public class DocumentLinkService {

    private final PurchaseOrderCommandService purchaseOrderCommandService;
    private final ProformaInvoiceCommandService proformaInvoiceCommandService;
    private final CommercialInvoiceJpaRepository commercialInvoiceJpaRepository;
    private final PackingListJpaRepository packingListJpaRepository;
    private final ShipmentOrderJpaRepository shipmentOrderJpaRepository;
    private final ProductionOrderRepository productionOrderRepository;
    private final DocumentJsonSupportService documentJsonSupportService;

    public DocumentLinkService(PurchaseOrderCommandService purchaseOrderCommandService,
                               ProformaInvoiceCommandService proformaInvoiceCommandService,
                               CommercialInvoiceJpaRepository commercialInvoiceJpaRepository,
                               PackingListJpaRepository packingListJpaRepository,
                               ShipmentOrderJpaRepository shipmentOrderJpaRepository,
                               ProductionOrderRepository productionOrderRepository,
                               DocumentJsonSupportService documentJsonSupportService) {
        this.purchaseOrderCommandService = purchaseOrderCommandService;
        this.proformaInvoiceCommandService = proformaInvoiceCommandService;
        this.commercialInvoiceJpaRepository = commercialInvoiceJpaRepository;
        this.packingListJpaRepository = packingListJpaRepository;
        this.shipmentOrderJpaRepository = shipmentOrderJpaRepository;
        this.productionOrderRepository = productionOrderRepository;
        this.documentJsonSupportService = documentJsonSupportService;
    }

    public void linkPurchaseOrderToProformaInvoice(String poId, String piId) {
        if (piId == null || piId.isBlank()) {
            return;
        }

        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        purchaseOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                purchaseOrder.getLinkedDocuments(), piId, "PI",
                purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
        purchaseOrderCommandService.save(purchaseOrder);

        ProformaInvoice proformaInvoice = proformaInvoiceCommandService.findById(piId);
        proformaInvoice.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                proformaInvoice.getLinkedDocuments(), poId, "PO",
                purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
        proformaInvoiceCommandService.save(proformaInvoice);
    }

    public void linkAutoGeneratedDocuments(String poId, String ciId, String plId, String shipmentOrderId) {
        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        purchaseOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                purchaseOrder.getLinkedDocuments(), ciId, "CI", "발행대기"));
        purchaseOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                purchaseOrder.getLinkedDocuments(), plId, "PL", "발행대기"));
        purchaseOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                purchaseOrder.getLinkedDocuments(), shipmentOrderId, "SO", "출하준비"));
        purchaseOrderCommandService.save(purchaseOrder);

        CommercialInvoice commercialInvoice = commercialInvoiceJpaRepository.findById(ciId).orElse(null);
        if (commercialInvoice != null) {
            commercialInvoice.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                    commercialInvoice.getLinkedDocuments(), poId, "PO",
                    purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
            if (purchaseOrder.getPiId() != null && !purchaseOrder.getPiId().isBlank()) {
                commercialInvoice.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                        commercialInvoice.getLinkedDocuments(), purchaseOrder.getPiId(), "PI", "CONFIRMED"));
            }
            commercialInvoiceJpaRepository.save(commercialInvoice);
        }

        PackingList packingList = packingListJpaRepository.findById(plId).orElse(null);
        if (packingList != null) {
            packingList.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                    packingList.getLinkedDocuments(), poId, "PO",
                    purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
            if (purchaseOrder.getPiId() != null && !purchaseOrder.getPiId().isBlank()) {
                packingList.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                        packingList.getLinkedDocuments(), purchaseOrder.getPiId(), "PI", "CONFIRMED"));
            }
            packingListJpaRepository.save(packingList);
        }

        ShipmentOrder shipmentOrder = shipmentOrderJpaRepository.findById(shipmentOrderId).orElse(null);
        if (shipmentOrder != null) {
            shipmentOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                    shipmentOrder.getLinkedDocuments(), poId, "PO",
                    purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
            if (purchaseOrder.getPiId() != null && !purchaseOrder.getPiId().isBlank()) {
                shipmentOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                        shipmentOrder.getLinkedDocuments(), purchaseOrder.getPiId(), "PI", "CONFIRMED"));
            }
            shipmentOrderJpaRepository.save(shipmentOrder);
        }
    }

    public void linkProductionOrder(String poId, String productionOrderId) {
        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        purchaseOrder.setLinkedDocuments(documentJsonSupportService.appendLinkedDocument(
                purchaseOrder.getLinkedDocuments(), productionOrderId, "MO", "진행중"));
        purchaseOrderCommandService.save(purchaseOrder);

        ProductionOrder productionOrder = productionOrderRepository.findById(productionOrderId).orElse(null);
        if (productionOrder != null) {
            productionOrder.setPoNo(poId);
            productionOrderRepository.save(productionOrder);
        }
    }
}
