package com.team2.documents.command.application.service;

import org.springframework.stereotype.Service;
@Service
public class DocumentLinkService {

    private final DocumentLinkMutationService documentLinkMutationService;

    public DocumentLinkService(DocumentLinkMutationService documentLinkMutationService) {
        this.documentLinkMutationService = documentLinkMutationService;
    }

    public void linkPurchaseOrderToProformaInvoice(String poId, String piId) {
        if (piId == null || piId.isBlank()) {
            return;
        }
        documentLinkMutationService.linkPurchaseOrderToProformaInvoice(poId, piId);
    }

    public void linkAutoGeneratedDocuments(String poId, String ciId, String plId, String shipmentOrderId) {
        documentLinkMutationService.linkAutoGeneratedDocuments(poId, ciId, plId, shipmentOrderId);
    }

    public void linkProductionOrder(String poId, String productionOrderId) {
        documentLinkMutationService.linkProductionOrder(poId, productionOrderId);
    }
}
