package com.team2.documents.command.application.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.team2.documents.command.domain.entity.ProformaInvoice;
import com.team2.documents.command.domain.entity.ProductionOrder;
import com.team2.documents.command.domain.entity.PurchaseOrder;
import com.team2.documents.command.domain.entity.ShipmentOrder;
import com.team2.documents.command.domain.repository.ProductionOrderRepository;
import com.team2.documents.command.domain.repository.ShipmentOrderJpaRepository;

@Service
@Transactional
public class DocumentLinkMutationService {

    private final PurchaseOrderCommandService purchaseOrderCommandService;
    private final ProformaInvoiceCommandService proformaInvoiceCommandService;
    private final ShipmentOrderJpaRepository shipmentOrderJpaRepository;
    private final ProductionOrderRepository productionOrderRepository;
    private final DocumentLinkBuilderService documentLinkBuilderService;

    public DocumentLinkMutationService(PurchaseOrderCommandService purchaseOrderCommandService,
                                       ProformaInvoiceCommandService proformaInvoiceCommandService,
                                       ShipmentOrderJpaRepository shipmentOrderJpaRepository,
                                       ProductionOrderRepository productionOrderRepository,
                                       DocumentLinkBuilderService documentLinkBuilderService) {
        this.purchaseOrderCommandService = purchaseOrderCommandService;
        this.proformaInvoiceCommandService = proformaInvoiceCommandService;
        this.shipmentOrderJpaRepository = shipmentOrderJpaRepository;
        this.productionOrderRepository = productionOrderRepository;
        this.documentLinkBuilderService = documentLinkBuilderService;
    }

    public void linkPurchaseOrderToProformaInvoice(String poId, String piId) {
        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        purchaseOrder.setLinkedDocuments(documentLinkBuilderService.append(
                purchaseOrder.getLinkedDocuments(), piId, "PI",
                purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
        purchaseOrderCommandService.save(purchaseOrder);

        ProformaInvoice proformaInvoice = proformaInvoiceCommandService.findById(piId);
        proformaInvoice.setLinkedDocuments(documentLinkBuilderService.append(
                proformaInvoice.getLinkedDocuments(), poId, "PO",
                purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
        proformaInvoiceCommandService.save(proformaInvoice);
    }

    public void linkAutoGeneratedDocuments(String poId, String ciId, String plId, String shipmentOrderId) {
        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        purchaseOrder.setLinkedDocuments(documentLinkBuilderService.append(
                purchaseOrder.getLinkedDocuments(), ciId, "CI", "발행대기"));
        purchaseOrder.setLinkedDocuments(documentLinkBuilderService.append(
                purchaseOrder.getLinkedDocuments(), plId, "PL", "발행대기"));
        purchaseOrder.setLinkedDocuments(documentLinkBuilderService.append(
                purchaseOrder.getLinkedDocuments(), shipmentOrderId, "SO", "출하준비"));
        purchaseOrderCommandService.save(purchaseOrder);

        ShipmentOrder shipmentOrder = shipmentOrderJpaRepository.findByShipmentOrderCode(shipmentOrderId).orElse(null);
        if (shipmentOrder == null) {
            return;
        }

        shipmentOrder.setLinkedDocuments(documentLinkBuilderService.append(
                shipmentOrder.getLinkedDocuments(), poId, "PO",
                purchaseOrder.getStatus() == null ? null : purchaseOrder.getStatus().name()));
        if (purchaseOrder.getPiId() != null && !purchaseOrder.getPiId().isBlank()) {
            shipmentOrder.setLinkedDocuments(documentLinkBuilderService.append(
                    shipmentOrder.getLinkedDocuments(), purchaseOrder.getPiId(), "PI", "CONFIRMED"));
        }
        shipmentOrderJpaRepository.save(shipmentOrder);
    }

    public void linkProductionOrder(String poId, String productionOrderId) {
        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        purchaseOrder.setLinkedDocuments(documentLinkBuilderService.append(
                purchaseOrder.getLinkedDocuments(), productionOrderId, "MO", "진행중"));
        purchaseOrderCommandService.save(purchaseOrder);

        ProductionOrder productionOrder = productionOrderRepository.findByProductionOrderCode(productionOrderId).orElse(null);
        if (productionOrder != null) {
            productionOrder.setPoCode(poId);
            productionOrderRepository.save(productionOrder);
        }
    }
}
