package com.team2.documents.command.application.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.team2.documents.command.domain.entity.PurchaseOrder;
import com.team2.documents.command.domain.entity.enums.PurchaseOrderStatus;
import com.team2.documents.command.domain.repository.CommercialInvoiceRepository;
import com.team2.documents.command.domain.repository.PackingListRepository;
import com.team2.documents.command.domain.repository.ShipmentOrderRepository;

@Service
@Transactional
public class PurchaseOrderDocumentGenerationService {

    private final PurchaseOrderCommandService purchaseOrderCommandService;
    private final CommercialInvoiceRepository commercialInvoiceRepository;
    private final PackingListRepository packingListRepository;
    private final ShipmentOrderRepository shipmentOrderRepository;
    private final DocumentNumberGeneratorService documentNumberGeneratorService;
    private final DocumentLinkService documentLinkService;
    private final DocumentRevisionHistoryService documentRevisionHistoryService;

    public PurchaseOrderDocumentGenerationService(PurchaseOrderCommandService purchaseOrderCommandService,
                                                  CommercialInvoiceRepository commercialInvoiceRepository,
                                                  PackingListRepository packingListRepository,
                                                  ShipmentOrderRepository shipmentOrderRepository,
                                                  DocumentNumberGeneratorService documentNumberGeneratorService,
                                                  DocumentLinkService documentLinkService,
                                                  DocumentRevisionHistoryService documentRevisionHistoryService) {
        this.purchaseOrderCommandService = purchaseOrderCommandService;
        this.commercialInvoiceRepository = commercialInvoiceRepository;
        this.packingListRepository = packingListRepository;
        this.shipmentOrderRepository = shipmentOrderRepository;
        this.documentNumberGeneratorService = documentNumberGeneratorService;
        this.documentLinkService = documentLinkService;
        this.documentRevisionHistoryService = documentRevisionHistoryService;
    }

    public void generateOnConfirmation(String poId) {
        PurchaseOrder purchaseOrder = purchaseOrderCommandService.findById(poId);
        if (!PurchaseOrderStatus.CONFIRMED.equals(purchaseOrder.getStatus())) {
            throw new IllegalStateException("확정 상태의 PO만 자동 생성 문서를 가질 수 있습니다.");
        }

        String ciId = documentNumberGeneratorService.nextCommercialInvoiceId();
        String plId = documentNumberGeneratorService.nextPackingListId();
        String shipmentOrderId = documentNumberGeneratorService.nextShipmentOrderId();

        commercialInvoiceRepository.createFromPurchaseOrder(poId, ciId);
        packingListRepository.createFromPurchaseOrder(poId, plId);
        shipmentOrderRepository.createFromPurchaseOrder(poId, shipmentOrderId);

        documentLinkService.linkAutoGeneratedDocuments(poId, ciId, plId, shipmentOrderId);
        documentRevisionHistoryService.recordPurchaseOrderEvent(
                poId,
                "GENERATE_FOLLOW_UP_DOCUMENTS",
                purchaseOrder.getManagerId(),
                purchaseOrder.getStatus().name(),
                "CI/PL/SO 문서를 자동 생성했습니다."
        );
    }
}
