package com.team2.documents.service;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.team2.documents.entity.PurchaseOrder;
import com.team2.documents.entity.PurchaseOrderStatus;
import com.team2.documents.repository.CommercialInvoiceRepository;
import com.team2.documents.repository.PackingListRepository;
import com.team2.documents.repository.PurchaseOrderRepository;
import com.team2.documents.repository.ShipmentOrderRepository;

@ExtendWith(MockitoExtension.class)
class PurchaseOrderDocumentGenerationServiceTest {

    @Mock
    private PurchaseOrderRepository purchaseOrderRepository;

    @Mock
    private CommercialInvoiceRepository commercialInvoiceRepository;

    @Mock
    private PackingListRepository packingListRepository;

    @Mock
    private ShipmentOrderRepository shipmentOrderRepository;

    @InjectMocks
    private PurchaseOrderDocumentGenerationService purchaseOrderDocumentGenerationService;

    @Test
    @DisplayName("확정 상태의 PO는 CI, PL, 출하지시서를 자동 생성한다")
    void generateDocuments_whenPurchaseOrderIsConfirmed_thenCreatesAutoGeneratedDocuments() {
        // given
        String poId = "PO2025-0001";
        PurchaseOrder purchaseOrder = new PurchaseOrder(poId, PurchaseOrderStatus.CONFIRMED);

        when(purchaseOrderRepository.findById(poId)).thenReturn(Optional.of(purchaseOrder));

        // when
        purchaseOrderDocumentGenerationService.generateOnConfirmation(poId);

        // then
        verify(commercialInvoiceRepository).createFromPurchaseOrder(poId);
        verify(packingListRepository).createFromPurchaseOrder(poId);
        verify(shipmentOrderRepository).createFromPurchaseOrder(poId);
    }

    @Test
    @DisplayName("PO 정보가 없으면 자동 생성 시 예외가 발생한다")
    void generateDocuments_whenPurchaseOrderDoesNotExist_thenThrowsException() {
        // given
        String poId = "PO2025-9999";
        when(purchaseOrderRepository.findById(poId)).thenReturn(Optional.empty());

        // when & then
        assertThrows(IllegalArgumentException.class,
                () -> purchaseOrderDocumentGenerationService.generateOnConfirmation(poId));
    }

    @Test
    @DisplayName("확정 상태가 아닌 PO는 자동 생성할 수 없다")
    void generateDocuments_whenPurchaseOrderIsNotConfirmed_thenThrowsException() {
        // given
        String poId = "PO2025-0001";
        PurchaseOrder purchaseOrder = new PurchaseOrder(poId, PurchaseOrderStatus.APPROVAL_PENDING);

        when(purchaseOrderRepository.findById(poId)).thenReturn(Optional.of(purchaseOrder));

        // when & then
        assertThrows(IllegalStateException.class,
                () -> purchaseOrderDocumentGenerationService.generateOnConfirmation(poId));
    }
}
